### ISSUE TITLE
Property 'database' does not exist on type 'FirebaseApp'

### ISSUE THREAD

**Issue by xer0design** [Festify/app#179]
Hey guys,

I believe I've everything setup correctly, I've all the config files setup and have the firebase project setup but when I try to build or serve I get the following error, any suggestions on what I might be doing wrong? 
```
> festify-client@0.1.0 serve /home/florian/app
> rollup -c --watch

[!] (rpt2 plugin) Error: /home/florian/app/src/sagas/party-data.ts(90,22): semantic error TS2339 Property 'database' does not exist on type 'FirebaseApp'.
src/sagas/party-data.ts
Error: /home/florian/app/src/sagas/party-data.ts(90,22): semantic error TS2339 Property 'database' does not exist on type 'FirebaseApp'.
    at error (/home/florian/app/node_modules/rollup/dist/rollup.js:199:15)
    at Object.error (/home/florian/app/node_modules/rollup/dist/rollup.js:17551:21)
    at RollupContext.error (/home/florian/app/node_modules/rollup-plugin-typescript2/src/rollupcontext.ts:36:18)
    at /home/florian/app/node_modules/rollup-plugin-typescript2/src/print-diagnostics.ts:41:11
    at arrayEach (/home/florian/app/node_modules/rollup-plugin-typescript2/node_modules/lodash/lodash.js:516:11)
    at forEach (/home/florian/app/node_modules/rollup-plugin-typescript2/node_modules/lodash/lodash.js:9342:14)
    at printDiagnostics (/home/florian/app/node_modules/rollup-plugin-typescript2/src/print-diagnostics.ts:9:2)
    at Object.transform (/home/florian/app/node_modules/rollup-plugin-typescript2/src/index.ts:244:5)
    at /home/florian/app/node_modules/rollup/dist/rollup.js:17556:48
    at <anonymous>

1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! festify-client@0.1.0 serve: `rollup -c --watch`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the festify-client@0.1.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-05-21T21_27_52_494Z-debug.log
```

The log shows the following
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run-script', 'serve' ]
2 info using npm@5.6.0
3 info using node@v8.11.2
4 verbose run-script [ 'preserve', 'serve', 'postserve' ]
5 info lifecycle festify-client@0.1.0~preserve: festify-client@0.1.0
6 info lifecycle festify-client@0.1.0~serve: festify-client@0.1.0
7 verbose lifecycle festify-client@0.1.0~serve: unsafe-perm in lifecycle true
8 verbose lifecycle festify-client@0.1.0~serve: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/florian/app/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle festify-client@0.1.0~serve: CWD: /home/florian/app
10 silly lifecycle festify-client@0.1.0~serve: Args: [ '-c', 'rollup -c --watch' ]
11 silly lifecycle festify-client@0.1.0~serve: Returned: code: 1  signal: null
12 info lifecycle festify-client@0.1.0~serve: Failed to exec serve script
13 verbose stack Error: festify-client@0.1.0 serve: `rollup -c --watch`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid festify-client@0.1.0
15 verbose cwd /home/florian/app
16 verbose Linux 4.9.0-6-amd64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run-script" "serve"
18 verbose node v8.11.2
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error festify-client@0.1.0 serve: `rollup -c --watch`
22 error Exit status 1
23 error Failed at the festify-client@0.1.0 serve script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
When trying to serve it, it briefly pops up that it's being served on port 3000 but then after a second or two it crashes to display the error, this is what it displays before failing
```
rollup v0.59.2
bundles src/index.ts → build/index.js...
rpt2: options error TS5055 Cannot write file '/home/florian/app/common.config.js' because it would overwrite input file.
rpt2: options error TS5055 Cannot write file '/home/florian/app/firebase.config.js' because it would overwrite input file.
rpt2: options error TS5055 Cannot write file '/home/florian/app/spotify.config.js' because it would overwrite input file.
[Browsersync] Access URLs:
 --------------------------------
    Local: http://localhost:3000
 External: http://10.132.0.2:3000
 --------------------------------
[Browsersync] Serving files from: build
```

**Comment by NeoLegends** [comment]
Could you try using yarn for installation instead of npm? We use yarn's lockfile to pin dependencies to exact versions and this doesn't seem to be the case here.

**Comment by xer0design** [comment]
Hey, that seems to have fixed that issue all right, thanks! It's still not building or serving, getting caught somewhere else now but I should be able to troubleshoot that myself from here. Thanks.

**Comment by NeoLegends** [comment]
Yeah so I just made a dependency upgrade and now I'm seeing the same errors. :)

**Comment by xer0design** [comment]
Is it possible to use an older version of firebase while we wait for a fix?

**Comment by NeoLegends** [comment]
Sure. If you‘re using yarn you‘re already using the older version of Firebase, since that it whats pinned through the lockfile. They introduced that error through a bugfix (last number) which is why npm (without the npm-specific lockfile) installs have the bug (because npm will install the latest possible version) and yarn installs don‘t.

**Comment by xer0design** [comment]
Ah okay, there's something else going on so, I can successfully build it and copy it to apache2, or I can serve it, but both times I just get a grey screen with "BrowserSync: connected" appearing in the corner (http://35.187.31.74:3000/ and http://35.187.31.74/build), any ideas?

**Comment by xer0design** [comment]
```
$ sudo yarn serve
yarn run v1.6.0
$ rollup -c --watch

rollup v0.59.1
bundles src/index.ts → build/index.js...
rpt2: options error TS5055 Cannot write file '/home/xer0design/app/common.config.js' because it would overwrite input file.
rpt2: options error TS5055 Cannot write file '/home/xer0design/app/firebase.config.js' because it would overwrite input file.
rpt2: options error TS5055 Cannot write file '/home/xer0design/app/spotify.config.js' because it would overwrite input file.
[Browsersync] Access URLs:
 --------------------------------
    Local: http://localhost:3000
 External: http://10.132.0.5:3000
 --------------------------------
[Browsersync] Serving files from: build
Circular dependency: node_modules/redux-saga/es/internal/io.js -> node_modules/redux-saga/es/internal/sagaHelpers/index.js -> node_modules/redux-saga/es/internal/sagaHelpers/takeEvery.js -> node_modules/redux-saga/es/internal/io.js
Circular dependency: node_modules/redux-saga/es/internal/io.js -> node_modules/redux-saga/es/internal/sagaHelpers/index.js -> node_modules/redux-saga/es/internal/sagaHelpers/takeLatest.js -> node_modules/redux-saga/es/internal/io.js
Circular dependency: node_modules/redux-saga/es/internal/io.js -> node_modules/redux-saga/es/internal/sagaHelpers/index.js -> node_modules/redux-saga/es/internal/sagaHelpers/throttle.js -> node_modules/redux-saga/es/internal/io.js
Circular dependency: src/store.ts -> src/sagas/index.ts -> src/sagas/party-data.ts -> src/store.ts
created build/index.js in 17.6s

[2018-05-23 21:11:18] waiting for changes...
[Browsersync] Reloading Browsers...

```

**Comment by NeoLegends** [comment]
Sure looks right. Which browser are you using? We‘ve noticed some problems with Firefox in the dev version (on prod everythings fine).

**Comment by NeoLegends** [comment]
In both cases looking at your browsers console will help.

**Comment by xer0design** [comment]
Chrome and Safari, Dev console just has a warning about Spotify keys

**Comment by NeoLegends** [comment]
Could you tell me exactly the warning text?

**Comment by NeoLegends** [comment]
> [Violation] Avoid using document.write().

Yeah this is expected.

> [Violation] jquery.min.js:3 [Violation] Added synchronous DOM mutation listener to a 'DOMNodeInserted' event. Consider using MutationObserver to make the page more responsive.

Probably a browser plugin.

Could you check whether Festify works in incognito mode (or without browser extensions)? We've had cases where browser extensions were breaking Festify.

**Comment by xer0design** [comment]
I've tried incognito, chrome Canary and Safari and all have the same results for me, they all just load grey and say "Browsersync: connected" for a second and nothing else happens apart from the console error

**Comment by xer0design** [comment]
I'm running Debian stretch by the way, would you suggest another distro that might yield better results?

**Comment by NeoLegends** [comment]
> Uncaught RavenConfigError {name: "RavenConfigError", message: "Do not specify your secret key in the DSN. See: http://bit.ly/raven-secret-key"}

Okay, I see this error as well when I go to your site. This is probably the culprit here. What does your `SENTRY_URL` env variable look like (don't post it in its entirety here, just the rough schema). It should be something like `https://<lots of random characters>@sentry.io/<some more random characters>`.

**Comment by xer0design** [comment]
It follows the format in your comment https://i.imgur.com/KNkb28J.jpg

**Comment by NeoLegends** [comment]
Googling the error message lead me to this issue here https://github.com/getsentry/sentry/issues/3696. Seems like there are two different sentry URLs and you're using the wrong one (the secret one, while you'd need be using the public one). See https://docs.sentry.io/quickstart/#configure-the-dsn.

**Comment by xer0design** [comment]
Woah, that fixed it, it's live! Thank you so much for your help
