### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by goshdark138** [Festify/app#230]
please help me to build

C:\Users\AISON\Desktop\app-master>yarn serve
yarn run v1.9.4
$ rollup -c --watch
rollup v0.62.0
rollup v0.62.0
bundles src\index.ts → build\index.js...
.

**Comment by NeoLegends** [comment]
Read the readme and try again.

**Comment by NeoLegends** [comment]
Seriously, read the readme! ;)

> Set up a _dedicated and paid_ Firebase project

Functions only work correctly in firebase projects with billing enabled.

Also really make sure you have all the environment files (and their names!) correct. See this https://github.com/Festify/app/issues/184 issue for reference.

**Comment by NeoLegends** [comment]
Closing for inactivity. Please feel free to reopen or open another ticket. :)

**Comment by goshdark138** [comment]
@NeoLegends please help me, I already have the payment account for firebase project

https://us-central1-fiesta-a0248.cloudfunctions.net/exchangeCode

error 500

**Comment by goshdark138** [comment]
@NeoLegends I apologize for not having clarity in the way of asking, but I am new in this programming, every time I look for information I confuse 

https://www.dropbox.com/s/2snqpdgkw33m72p/cloud_function_function_name_exchangeCode_region_us-central1__logs__2018-12-04T08-21.json?dl=0

**Comment by goshdark138** [comment]
Unhandled error TypeError: Cipher data must be a string or a buffer
    at TypeError (native)
    at Cipher.update (crypto.js:146:26)
    at Object.encrypt (/user_code/dist/lib/utils.js:9:23)
    at Object.<anonymous> (/user_code/dist/lib/spotify-auth.js:124:38)
    at next (native)
    at fulfilled (/user_code/node_modules/tslib/tslib.js:104:62)

**Comment by goshdark138** [comment]
@NeoLegends excuse my insistence.
I do not have audio when playing the track,
any ideas

**Comment by NeoLegends** [comment]
Did you fix the previous error you posted?

Let's discuss this in a new ticket. It's good practice to keep to one topic within one ticket.
