### ISSUE TITLE
@festify\redux-little-router: SyntaxError: Export 'Link' is not defined (14:0)

### ISSUE THREAD

**Issue by marienfeldtom** [Festify/app#266]
I get this error when I do rollup -c.

`[!] (commonjs plugin) SyntaxError: Export 'Link' is not defined (14:0) in C:\Users\Anwender\Desktop\app\node_modules\@festify\redux-little-router\es\index.js
node_modules\@festify\redux-little-router\es\index.js (14:0)
12: routerForBrowser, routerForExpress, routerForHapi, routerForHash, initializeCurrentLocation,
13: // React API
14: Link, PersistentQueryLink, Fragment,
    ^
15: // Public action creators
16: push, replace, go, goBack, goForward, block, unblock, replaceRoutes,
SyntaxError: Export 'Link' is not defined (14:0) in C:\Users\Anwender\Desktop\app\node_modules\@festify\redux-little-router\es\index.js
    at Object.pp$4.raise (C:\Users\Anwender\AppData\Roaming\npm\node_modules\rollup\node_modules\acorn\dist\acorn.js:2844:13)
    at Object.pp$1.parseTopLevel (C:\Users\Anwender\AppData\Roaming\npm\node_modules\rollup\node_modules\acorn\dist\acorn.js:757:16)
    at Object.parse (C:\Users\Anwender\AppData\Roaming\npm\node_modules\rollup\node_modules\acorn\dist\acorn.js:552:15)
    at Function.parse (C:\Users\Anwender\AppData\Roaming\npm\node_modules\rollup\node_modules\acorn\dist\acorn.js:575:35)
    at Graph.contextParse (C:\Users\Anwender\AppData\Roaming\npm\node_modules\rollup\dist\rollup.js:17503:38)
    at tryParse (C:\Users\Anwender\Desktop\app\node_modules\rollup-plugin-commonjs\dist\rollup-plugin-commonjs.cjs.js:319:10)
    at checkEsModule (C:\Users\Anwender\Desktop\app\node_modules\rollup-plugin-commonjs\dist\rollup-plugin-commonjs.cjs.js:332:12)
    at C:\Users\Anwender\Desktop\app\node_modules\rollup-plugin-commonjs\dist\rollup-plugin-commonjs.cjs.js:893:16
    at <anonymous>`

**Comment by NeoLegends** [comment]
Hey, are you using `yarn` for the installation?

**Comment by marienfeldtom** [comment]
Thanks for the quick response. I used yarn for the installation yes. I couldnt build with yarn build because I was on a windows machine. I changed the yarn build command in package.json and now yarn build works. Thanks for your quick response. Issue can be closed.
